### ISSUE TITLE
incompatibility with `ntheorem` using `\declaretheorem`

### ISSUE THREAD

**Issue by GTM52** [muzimuzhi/thmtools#36]
`thmtools` seems to be incompatible with the package `ntheorem`, here is a minimal example:
```latex
\documentclass{article}
\usepackage{ntheorem, thmtools}
\declaretheorem[style = plain]{theorem}
\begin{document}
\begin{theorem}
    This is a theorem.
\end{theorem}
\end{document}
```
the error message is `Argument of \MakeUppercase has an extra }`.
This can be solved by setting `title = {title_name}` in the command,
but it could be uncomfortable when declaring many theorems at the same time.

Is there a more elegant way to solve this problem? Thanks for your help.

**Comment by muzimuzhi** [comment]
I pushed a fix in another way.  Feedbacks welcome.

**Comment by muzimuzhi** [comment]
A revised version is just pushed and I'm going to release a new version.

`\thmt@thmname` has been fully expanded inside `\protected@edef` since the first CTAN release of `thmtools` in 2008, see 
[`b89ec88`](https://github.com/muzimuzhi/thmtools/commit/b89ec8833c8aff7ecd5e172edea061cb076746ef#diff-ae0e09b8ec45f060ab6c6f11989ebb1ca8de04422b8f2a204945540ed57e0380R109-R124). Hence I decide to not modify this behavior, but only suppress the expansion of `\MakeUppercase`/`\MakeLowercase` if it is auto prepended to `\thmt@thmname`.

**Comment by GTM52** [comment]
It works perfectly, thanks for your help!
